export { AccountResource as Account } from './resources/Accounts.js';
export { AccountResource as Accounts } from './resources/Accounts.js';
export { AccountLinkResource as AccountLinks } from './resources/AccountLinks.js';
export { AccountSessionResource as AccountSessions } from './resources/AccountSessions.js';
export { ApplePayDomainResource as ApplePayDomains } from './resources/ApplePayDomains.js';
export { ApplicationFeeResource as ApplicationFees } from './resources/ApplicationFees.js';
export { BalanceResource as Balance } from './resources/Balance.js';
export { BalanceResource as Balances } from './resources/Balance.js';
export { BalanceSettingResource as BalanceSettings } from './resources/BalanceSettings.js';
export { BalanceTransactionResource as BalanceTransactions } from './resources/BalanceTransactions.js';
export { ChargeResource as Charges } from './resources/Charges.js';
export { ConfirmationTokenResource as ConfirmationTokens } from './resources/ConfirmationTokens.js';
export { CountrySpecResource as CountrySpecs } from './resources/CountrySpecs.js';
export { CouponResource as Coupons } from './resources/Coupons.js';
export { CreditNoteResource as CreditNotes } from './resources/CreditNotes.js';
export { CustomerResource as Customers } from './resources/Customers.js';
export { CustomerSessionResource as CustomerSessions } from './resources/CustomerSessions.js';
export { DisputeResource as Disputes } from './resources/Disputes.js';
export { EphemeralKeyResource as EphemeralKeys } from './resources/EphemeralKeys.js';
export { EventResource as Events } from './resources/Events.js';
export { ExchangeRateResource as ExchangeRates } from './resources/ExchangeRates.js';
export { FileResource as Files } from './resources/Files.js';
export { FileLinkResource as FileLinks } from './resources/FileLinks.js';
export { InvoiceResource as Invoices } from './resources/Invoices.js';
export { InvoiceItemResource as InvoiceItems } from './resources/InvoiceItems.js';
export { InvoicePaymentResource as InvoicePayments } from './resources/InvoicePayments.js';
export { InvoiceRenderingTemplateResource as InvoiceRenderingTemplates } from './resources/InvoiceRenderingTemplates.js';
export { MandateResource as Mandates } from './resources/Mandates.js';
export { OAuthResource } from './resources/OAuth.js';
export { PaymentAttemptRecordResource as PaymentAttemptRecords } from './resources/PaymentAttemptRecords.js';
export { PaymentIntentResource as PaymentIntents } from './resources/PaymentIntents.js';
export { PaymentLinkResource as PaymentLinks } from './resources/PaymentLinks.js';
export { PaymentMethodResource as PaymentMethods } from './resources/PaymentMethods.js';
export { PaymentMethodConfigurationResource as PaymentMethodConfigurations } from './resources/PaymentMethodConfigurations.js';
export { PaymentMethodDomainResource as PaymentMethodDomains } from './resources/PaymentMethodDomains.js';
export { PaymentRecordResource as PaymentRecords } from './resources/PaymentRecords.js';
export { PayoutResource as Payouts } from './resources/Payouts.js';
export { PlanResource as Plans } from './resources/Plans.js';
export { PriceResource as Prices } from './resources/Prices.js';
export { ProductResource as Products } from './resources/Products.js';
export { PromotionCodeResource as PromotionCodes } from './resources/PromotionCodes.js';
export { QuoteResource as Quotes } from './resources/Quotes.js';
export { RefundResource as Refunds } from './resources/Refunds.js';
export { ReviewResource as Reviews } from './resources/Reviews.js';
export { SetupAttemptResource as SetupAttempts } from './resources/SetupAttempts.js';
export { SetupIntentResource as SetupIntents } from './resources/SetupIntents.js';
export { ShippingRateResource as ShippingRates } from './resources/ShippingRates.js';
export { SourceResource as Sources } from './resources/Sources.js';
export { SubscriptionResource as Subscriptions } from './resources/Subscriptions.js';
export { SubscriptionItemResource as SubscriptionItems } from './resources/SubscriptionItems.js';
export { SubscriptionScheduleResource as SubscriptionSchedules } from './resources/SubscriptionSchedules.js';
export { TaxCodeResource as TaxCodes } from './resources/TaxCodes.js';
export { TaxIdResource as TaxIds } from './resources/TaxIds.js';
export { TaxRateResource as TaxRates } from './resources/TaxRates.js';
export { TokenResource as Tokens } from './resources/Tokens.js';
export { TopupResource as Topups } from './resources/Topups.js';
export { TransferResource as Transfers } from './resources/Transfers.js';
export { WebhookEndpointResource as WebhookEndpoints } from './resources/WebhookEndpoints.js';
export declare const Apps: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Billing: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const BillingPortal: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Checkout: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Climate: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Entitlements: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const FinancialConnections: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Forwarding: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Identity: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Issuing: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Radar: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Reporting: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Sigma: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Tax: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Terminal: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const TestHelpers: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const Treasury: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
export declare const V2: new (stripe: import("./stripe.core.js").StripeClient) => import("./ResourceNamespace.js").StripeResourceNamespaceObject;
