plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "/opt/build/repo"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]