declare namespace Stripe {
  /**
   * The InvoiceSettings object.
   */
  interface InvoiceSettings {
    /**
     * Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
     */
    days_until_due?: number | null;
  }
}