declare namespace Stripe {
  /**
   * The Receipt object.
   */
  interface Receipt {
    /**
     * EMV tag 9F26, cryptogram generated by the integrated circuit chip.
     */
    application_cryptogram?: string | null;

    /**
     * Mnenomic of the Application Identifier.
     */
    application_preferred_name?: string | null;

    /**
     * Identifier for this transaction.
     */
    authorization_code?: string | null;

    /**
     * EMV tag 8A. A code returned by the card issuer.
     */
    authorization_response_code?: string | null;

    /**
     * How the cardholder verified ownership of the card.
     */
    cardholder_verification_method?: string | null;

    /**
     * EMV tag 84. Similar to the application identifier stored on the integrated circuit chip.
     */
    dedicated_file_name?: string | null;

    /**
     * The outcome of a series of EMV functions performed by the card reader.
     */
    terminal_verification_results?: string | null;

    /**
     * An indication of various EMV functions performed during the transaction.
     */
    transaction_status_information?: string | null;
  }
}