// File generated from our OpenAPI spec
'use strict';
const resourceNamespace = require('./ResourceNamespace');
module.exports = {
  Accounts: require('./resources/Account'),
  // Support Accounts for consistency, Account for backwards compatibility
  Account: require('./resources/Accounts'),
  AccountLinks: require('./resources/AccountLink'),
  ApplePayDomains: require('./resources/ApplePayDomain'),
  ApplicationFees: require('./resources/ApplicationFee'),
  Balance: require('./resources/Balance'),
  BalanceTransactions: require('./resources/BalanceTransaction'),
  Charges: require('./resources/Charge'),
  CountrySpecs: require('./resources/CountrySpec'),
  Coupons: require('./resources/Coupon'),
  CreditNotes: require('./resources/CreditNote'),
  Customers: require('./resources/Customer'),
  Disputes: require('./resources/Dispute'),
  EphemeralKeys: require('./resources/EphemeralKey'),
  Events: require('./resources/Event'),
  ExchangeRates: require('./resources/ExchangeRate'),
  Files: require('./resources/File'),
  FileLinks: require('./resources/FileLink'),
  Invoices: require('./resources/Invoice'),
  InvoiceItems: require('./resources/InvoiceItem'),
  Mandates: require('./resources/Mandate'),
  OAuth: require('./resources/OAuth'),
  PaymentIntents: require('./resources/PaymentIntent'),
  PaymentLinks: require('./resources/PaymentLink'),
  PaymentMethods: require('./resources/PaymentMethod'),
  Payouts: require('./resources/Payout'),
  Plans: require('./resources/Plan'),
  Prices: require('./resources/Price'),
  Products: require('./resources/Product'),
  PromotionCodes: require('./resources/PromotionCode'),
  Quotes: require('./resources/Quote'),
  Refunds: require('./resources/Refund'),
  Reviews: require('./resources/Review'),
  SetupAttempts: require('./resources/SetupAttempt'),
  SetupIntents: require('./resources/SetupIntent'),
  ShippingRates: require('./resources/ShippingRate'),
  Sources: require('./resources/Source'),
  Subscriptions: require('./resources/Subscription'),
  SubscriptionItems: require('./resources/SubscriptionItem'),
  SubscriptionSchedules: require('./resources/SubscriptionSchedule'),
  TaxCodes: require('./resources/TaxCode'),
  TaxRates: require('./resources/TaxRate'),
  Tokens: require('./resources/Token'),
  Topups: require('./resources/Topup'),
  Transfers: require('./resources/Transfer'),
  WebhookEndpoints: require('./resources/WebhookEndpoint'),
  Apps: resourceNamespace('apps', {
    Secrets: require('./resources/Apps/Secret'),
  }),
  BillingPortal: resourceNamespace('billingPortal', {
    Configurations: require('./resources/BillingPortal/Configuration'),
    Sessions: require('./resources/BillingPortal/Session'),
  }),
  Checkout: resourceNamespace('checkout', {
    Sessions: require('./resources/Checkout/Session'),
  }),
  FinancialConnections: resourceNamespace('financialConnections', {
    Accounts: require('./resources/FinancialConnections/Account'),
    Sessions: require('./resources/FinancialConnections/Session'),
  }),
  Identity: resourceNamespace('identity', {
    VerificationReports: require('./resources/Identity/VerificationReport'),
    VerificationSessions: require('./resources/Identity/VerificationSession'),
  }),
  Issuing: resourceNamespace('issuing', {
    Authorizations: require('./resources/Issuing/Authorization'),
    Cards: require('./resources/Issuing/Card'),
    Cardholders: require('./resources/Issuing/Cardholder'),
    Disputes: require('./resources/Issuing/Dispute'),
    Transactions: require('./resources/Issuing/Transaction'),
  }),
  Radar: resourceNamespace('radar', {
    EarlyFraudWarnings: require('./resources/Radar/EarlyFraudWarning'),
    ValueLists: require('./resources/Radar/ValueList'),
    ValueListItems: require('./resources/Radar/ValueListItem'),
  }),
  Reporting: resourceNamespace('reporting', {
    ReportRuns: require('./resources/Reporting/ReportRun'),
    ReportTypes: require('./resources/Reporting/ReportType'),
  }),
  Sigma: resourceNamespace('sigma', {
    ScheduledQueryRuns: require('./resources/Sigma/ScheduledQueryRun'),
  }),
  Terminal: resourceNamespace('terminal', {
    Configurations: require('./resources/Terminal/Configuration'),
    ConnectionTokens: require('./resources/Terminal/ConnectionToken'),
    Locations: require('./resources/Terminal/Location'),
    Readers: require('./resources/Terminal/Reader'),
  }),
  TestHelpers: resourceNamespace('testHelpers', {
    Customers: require('./resources/TestHelpers/Customer'),
    Refunds: require('./resources/TestHelpers/Refund'),
    TestClocks: require('./resources/TestHelpers/TestClock'),
    Issuing: resourceNamespace('issuing', {
      Cards: require('./resources/TestHelpers/Issuing/Card'),
    }),
    Terminal: resourceNamespace('terminal', {
      Readers: require('./resources/TestHelpers/Terminal/Reader'),
    }),
    Treasury: resourceNamespace('treasury', {
      InboundTransfers: require('./resources/TestHelpers/Treasury/InboundTransfer'),
      OutboundPayments: require('./resources/TestHelpers/Treasury/OutboundPayment'),
      OutboundTransfers: require('./resources/TestHelpers/Treasury/OutboundTransfer'),
      ReceivedCredits: require('./resources/TestHelpers/Treasury/ReceivedCredit'),
      ReceivedDebits: require('./resources/TestHelpers/Treasury/ReceivedDebit'),
    }),
  }),
  Treasury: resourceNamespace('treasury', {
    CreditReversals: require('./resources/Treasury/CreditReversal'),
    DebitReversals: require('./resources/Treasury/DebitReversal'),
    FinancialAccounts: require('./resources/Treasury/FinancialAccount'),
    InboundTransfers: require('./resources/Treasury/InboundTransfer'),
    OutboundPayments: require('./resources/Treasury/OutboundPayment'),
    OutboundTransfers: require('./resources/Treasury/OutboundTransfer'),
    ReceivedCredits: require('./resources/Treasury/ReceivedCredit'),
    ReceivedDebits: require('./resources/Treasury/ReceivedDebit'),
    Transactions: require('./resources/Treasury/Transaction'),
    TransactionEntries: require('./resources/Treasury/TransactionEntry'),
  }),
};
