// File copied from our code generator; changes here will be overwritten.

import {Stripe} from './stripe.core.js';
import * as Events from './resources/V2/Core/Events.js';

export interface UnhandledNotificationDetails {
  isKnownEventType: boolean;
}

export type FallbackCallback = (
  event: Events.UnknownEventNotification,
  client: Stripe,
  details: UnhandledNotificationDetails
) => Promise<void>;

// this is an internal-only type; we write a user-facing one separately
type HandlerCallback = (event: any, client: any) => Promise<void>;

// most languages can check if we have an UnknownEventNotification at runtime
// but JS only has interfaces so we fall back to a string match to determine known events
const KNOWN_EVENT_TYPES = new Set([
  // event-types: The beginning of the section generated from our OpenAPI spec
  'v1.account.application.authorized',
  'v1.account.application.deauthorized',
  'v1.account.external_account.created',
  'v1.account.external_account.deleted',
  'v1.account.external_account.updated',
  'v1.account.updated',
  'v1.account_signals[delinquency].created',
  'v1.application_fee.created',
  'v1.application_fee.refund.updated',
  'v1.application_fee.refunded',
  'v1.balance.available',
  'v1.billing.alert.triggered',
  'v1.billing.meter.error_report_triggered',
  'v1.billing.meter.no_meter_found',
  'v1.billing_portal.configuration.created',
  'v1.billing_portal.configuration.updated',
  'v1.billing_portal.session.created',
  'v1.capability.updated',
  'v1.cash_balance.funds_available',
  'v1.charge.captured',
  'v1.charge.dispute.closed',
  'v1.charge.dispute.created',
  'v1.charge.dispute.funds_reinstated',
  'v1.charge.dispute.funds_withdrawn',
  'v1.charge.dispute.updated',
  'v1.charge.expired',
  'v1.charge.failed',
  'v1.charge.pending',
  'v1.charge.refund.updated',
  'v1.charge.refunded',
  'v1.charge.succeeded',
  'v1.charge.updated',
  'v1.checkout.session.async_payment_failed',
  'v1.checkout.session.async_payment_succeeded',
  'v1.checkout.session.completed',
  'v1.checkout.session.expired',
  'v1.climate.order.canceled',
  'v1.climate.order.created',
  'v1.climate.order.delayed',
  'v1.climate.order.delivered',
  'v1.climate.order.product_substituted',
  'v1.climate.product.created',
  'v1.climate.product.pricing_updated',
  'v1.coupon.created',
  'v1.coupon.deleted',
  'v1.coupon.updated',
  'v1.credit_note.created',
  'v1.credit_note.updated',
  'v1.credit_note.voided',
  'v1.customer.created',
  'v1.customer.deleted',
  'v1.customer.subscription.created',
  'v1.customer.subscription.deleted',
  'v1.customer.subscription.paused',
  'v1.customer.subscription.pending_update_applied',
  'v1.customer.subscription.pending_update_expired',
  'v1.customer.subscription.resumed',
  'v1.customer.subscription.trial_will_end',
  'v1.customer.subscription.updated',
  'v1.customer.tax_id.created',
  'v1.customer.tax_id.deleted',
  'v1.customer.tax_id.updated',
  'v1.customer.updated',
  'v1.customer_cash_balance_transaction.created',
  'v1.entitlements.active_entitlement_summary.updated',
  'v1.file.created',
  'v1.financial_connections.account.created',
  'v1.financial_connections.account.deactivated',
  'v1.financial_connections.account.disconnected',
  'v1.financial_connections.account.reactivated',
  'v1.financial_connections.account.refreshed_balance',
  'v1.financial_connections.account.refreshed_ownership',
  'v1.financial_connections.account.refreshed_transactions',
  'v1.identity.verification_session.canceled',
  'v1.identity.verification_session.created',
  'v1.identity.verification_session.processing',
  'v1.identity.verification_session.redacted',
  'v1.identity.verification_session.requires_input',
  'v1.identity.verification_session.verified',
  'v1.invoice.created',
  'v1.invoice.deleted',
  'v1.invoice.finalization_failed',
  'v1.invoice.finalized',
  'v1.invoice.marked_uncollectible',
  'v1.invoice.overdue',
  'v1.invoice.overpaid',
  'v1.invoice.paid',
  'v1.invoice.payment_action_required',
  'v1.invoice.payment_failed',
  'v1.invoice.payment_succeeded',
  'v1.invoice.sent',
  'v1.invoice.upcoming',
  'v1.invoice.updated',
  'v1.invoice.voided',
  'v1.invoice.will_be_due',
  'v1.invoice_payment.paid',
  'v1.invoiceitem.created',
  'v1.invoiceitem.deleted',
  'v1.issuing_authorization.created',
  'v1.issuing_authorization.request',
  'v1.issuing_authorization.updated',
  'v1.issuing_card.created',
  'v1.issuing_card.updated',
  'v1.issuing_cardholder.created',
  'v1.issuing_cardholder.updated',
  'v1.issuing_dispute.closed',
  'v1.issuing_dispute.created',
  'v1.issuing_dispute.funds_reinstated',
  'v1.issuing_dispute.funds_rescinded',
  'v1.issuing_dispute.submitted',
  'v1.issuing_dispute.updated',
  'v1.issuing_personalization_design.activated',
  'v1.issuing_personalization_design.deactivated',
  'v1.issuing_personalization_design.rejected',
  'v1.issuing_personalization_design.updated',
  'v1.issuing_token.created',
  'v1.issuing_token.updated',
  'v1.issuing_transaction.created',
  'v1.issuing_transaction.purchase_details_receipt_updated',
  'v1.issuing_transaction.updated',
  'v1.mandate.updated',
  'v1.payment_intent.amount_capturable_updated',
  'v1.payment_intent.canceled',
  'v1.payment_intent.created',
  'v1.payment_intent.partially_funded',
  'v1.payment_intent.payment_failed',
  'v1.payment_intent.processing',
  'v1.payment_intent.requires_action',
  'v1.payment_intent.succeeded',
  'v1.payment_link.created',
  'v1.payment_link.updated',
  'v1.payment_method.attached',
  'v1.payment_method.automatically_updated',
  'v1.payment_method.detached',
  'v1.payment_method.updated',
  'v1.payout.canceled',
  'v1.payout.created',
  'v1.payout.failed',
  'v1.payout.paid',
  'v1.payout.reconciliation_completed',
  'v1.payout.updated',
  'v1.person.created',
  'v1.person.deleted',
  'v1.person.updated',
  'v1.plan.created',
  'v1.plan.deleted',
  'v1.plan.updated',
  'v1.price.created',
  'v1.price.deleted',
  'v1.price.updated',
  'v1.product.created',
  'v1.product.deleted',
  'v1.product.updated',
  'v1.promotion_code.created',
  'v1.promotion_code.updated',
  'v1.quote.accepted',
  'v1.quote.canceled',
  'v1.quote.created',
  'v1.quote.finalized',
  'v1.radar.early_fraud_warning.created',
  'v1.radar.early_fraud_warning.updated',
  'v1.refund.created',
  'v1.refund.failed',
  'v1.refund.updated',
  'v1.review.closed',
  'v1.review.opened',
  'v1.setup_intent.canceled',
  'v1.setup_intent.created',
  'v1.setup_intent.requires_action',
  'v1.setup_intent.setup_failed',
  'v1.setup_intent.succeeded',
  'v1.sigma.scheduled_query_run.created',
  'v1.source.canceled',
  'v1.source.chargeable',
  'v1.source.failed',
  'v1.source.refund_attributes_required',
  'v1.subscription_schedule.aborted',
  'v1.subscription_schedule.canceled',
  'v1.subscription_schedule.completed',
  'v1.subscription_schedule.created',
  'v1.subscription_schedule.expiring',
  'v1.subscription_schedule.released',
  'v1.subscription_schedule.updated',
  'v1.tax.settings.updated',
  'v1.tax_rate.created',
  'v1.tax_rate.updated',
  'v1.terminal.reader.action_failed',
  'v1.terminal.reader.action_succeeded',
  'v1.terminal.reader.action_updated',
  'v1.test_helpers.test_clock.advancing',
  'v1.test_helpers.test_clock.created',
  'v1.test_helpers.test_clock.deleted',
  'v1.test_helpers.test_clock.internal_failure',
  'v1.test_helpers.test_clock.ready',
  'v1.topup.canceled',
  'v1.topup.created',
  'v1.topup.failed',
  'v1.topup.reversed',
  'v1.topup.succeeded',
  'v1.transfer.created',
  'v1.transfer.reversed',
  'v1.transfer.updated',
  'v2.billing.cadence.billed',
  'v2.billing.cadence.canceled',
  'v2.billing.cadence.created',
  'v2.billing.contract.activated',
  'v2.billing.contract.canceled',
  'v2.billing.contract.created',
  'v2.billing.contract.ended',
  'v2.billing.contract.updated',
  'v2.billing.license_fee.created',
  'v2.billing.license_fee.updated',
  'v2.billing.license_fee_version.created',
  'v2.billing.licensed_item.created',
  'v2.billing.licensed_item.updated',
  'v2.billing.metered_item.created',
  'v2.billing.metered_item.updated',
  'v2.billing.pricing_plan.created',
  'v2.billing.pricing_plan.updated',
  'v2.billing.pricing_plan_component.created',
  'v2.billing.pricing_plan_component.updated',
  'v2.billing.pricing_plan_subscription.collection_awaiting_customer_action',
  'v2.billing.pricing_plan_subscription.collection_current',
  'v2.billing.pricing_plan_subscription.collection_past_due',
  'v2.billing.pricing_plan_subscription.collection_paused',
  'v2.billing.pricing_plan_subscription.collection_unpaid',
  'v2.billing.pricing_plan_subscription.servicing_activated',
  'v2.billing.pricing_plan_subscription.servicing_canceled',
  'v2.billing.pricing_plan_subscription.servicing_paused',
  'v2.billing.pricing_plan_version.created',
  'v2.billing.rate_card.created',
  'v2.billing.rate_card.updated',
  'v2.billing.rate_card_custom_pricing_unit_overage_rate.created',
  'v2.billing.rate_card_rate.created',
  'v2.billing.rate_card_subscription.activated',
  'v2.billing.rate_card_subscription.canceled',
  'v2.billing.rate_card_subscription.collection_awaiting_customer_action',
  'v2.billing.rate_card_subscription.collection_current',
  'v2.billing.rate_card_subscription.collection_past_due',
  'v2.billing.rate_card_subscription.collection_paused',
  'v2.billing.rate_card_subscription.collection_unpaid',
  'v2.billing.rate_card_subscription.servicing_activated',
  'v2.billing.rate_card_subscription.servicing_canceled',
  'v2.billing.rate_card_subscription.servicing_paused',
  'v2.billing.rate_card_version.created',
  'v2.commerce.product_catalog.imports.failed',
  'v2.commerce.product_catalog.imports.processing',
  'v2.commerce.product_catalog.imports.succeeded',
  'v2.commerce.product_catalog.imports.succeeded_with_errors',
  'v2.core.account.closed',
  'v2.core.account.created',
  'v2.core.account.updated',
  'v2.core.account[configuration.card_creator].capability_status_updated',
  'v2.core.account[configuration.card_creator].updated',
  'v2.core.account[configuration.customer].capability_status_updated',
  'v2.core.account[configuration.customer].updated',
  'v2.core.account[configuration.merchant].capability_status_updated',
  'v2.core.account[configuration.merchant].updated',
  'v2.core.account[configuration.money_manager].capability_status_updated',
  'v2.core.account[configuration.money_manager].updated',
  'v2.core.account[configuration.recipient].capability_status_updated',
  'v2.core.account[configuration.recipient].updated',
  'v2.core.account[defaults].updated',
  'v2.core.account[future_requirements].updated',
  'v2.core.account[identity].updated',
  'v2.core.account[requirements].updated',
  'v2.core.account_link.returned',
  'v2.core.account_person.created',
  'v2.core.account_person.deleted',
  'v2.core.account_person.updated',
  'v2.core.account_signals.fraudulent_website_ready',
  'v2.core.approval_request.approved',
  'v2.core.approval_request.canceled',
  'v2.core.approval_request.created',
  'v2.core.approval_request.expired',
  'v2.core.approval_request.failed',
  'v2.core.approval_request.rejected',
  'v2.core.approval_request.succeeded',
  'v2.core.batch_job.batch_failed',
  'v2.core.batch_job.canceled',
  'v2.core.batch_job.completed',
  'v2.core.batch_job.created',
  'v2.core.batch_job.ready_for_upload',
  'v2.core.batch_job.timeout',
  'v2.core.batch_job.updated',
  'v2.core.batch_job.upload_timeout',
  'v2.core.batch_job.validating',
  'v2.core.batch_job.validation_failed',
  'v2.core.claimable_sandbox.claimed',
  'v2.core.claimable_sandbox.created',
  'v2.core.claimable_sandbox.expired',
  'v2.core.claimable_sandbox.expiring',
  'v2.core.claimable_sandbox.updated',
  'v2.core.event_destination.ping',
  'v2.core.health.api_error.firing',
  'v2.core.health.api_error.resolved',
  'v2.core.health.api_latency.firing',
  'v2.core.health.api_latency.resolved',
  'v2.core.health.authorization_rate_drop.firing',
  'v2.core.health.authorization_rate_drop.resolved',
  'v2.core.health.elements_error.firing',
  'v2.core.health.elements_error.resolved',
  'v2.core.health.event_generation_failure.resolved',
  'v2.core.health.fraud_rate.increased',
  'v2.core.health.invoice_count_dropped.firing',
  'v2.core.health.invoice_count_dropped.resolved',
  'v2.core.health.issuing_authorization_request_errors.firing',
  'v2.core.health.issuing_authorization_request_errors.resolved',
  'v2.core.health.issuing_authorization_request_timeout.firing',
  'v2.core.health.issuing_authorization_request_timeout.resolved',
  'v2.core.health.meter_event_summaries_delayed.firing',
  'v2.core.health.meter_event_summaries_delayed.resolved',
  'v2.core.health.payment_method_error.firing',
  'v2.core.health.payment_method_error.resolved',
  'v2.core.health.sepa_debit_delayed.firing',
  'v2.core.health.sepa_debit_delayed.resolved',
  'v2.core.health.traffic_volume_drop.firing',
  'v2.core.health.traffic_volume_drop.resolved',
  'v2.core.health.webhook_latency.firing',
  'v2.core.health.webhook_latency.resolved',
  'v2.data.reporting.query_run.created',
  'v2.data.reporting.query_run.failed',
  'v2.data.reporting.query_run.succeeded',
  'v2.data.reporting.query_run.updated',
  'v2.extend.extension_run.failed',
  'v2.extend.workflow_run.failed',
  'v2.extend.workflow_run.started',
  'v2.extend.workflow_run.succeeded',
  'v2.iam.api_key.created',
  'v2.iam.api_key.default_secret_revealed',
  'v2.iam.api_key.expired',
  'v2.iam.api_key.permissions_updated',
  'v2.iam.api_key.rotated',
  'v2.iam.api_key.updated',
  'v2.iam.stripe_access_grant.approved',
  'v2.iam.stripe_access_grant.canceled',
  'v2.iam.stripe_access_grant.denied',
  'v2.iam.stripe_access_grant.removed',
  'v2.iam.stripe_access_grant.requested',
  'v2.iam.stripe_access_grant.updated',
  'v2.money_management.adjustment.created',
  'v2.money_management.debit_dispute.failed',
  'v2.money_management.debit_dispute.submitted',
  'v2.money_management.debit_dispute.succeeded',
  'v2.money_management.financial_account.created',
  'v2.money_management.financial_account.updated',
  'v2.money_management.financial_account_statement.created',
  'v2.money_management.financial_account_statement.restated',
  'v2.money_management.financial_address.activated',
  'v2.money_management.financial_address.failed',
  'v2.money_management.inbound_transfer.available',
  'v2.money_management.inbound_transfer.bank_debit_failed',
  'v2.money_management.inbound_transfer.bank_debit_processing',
  'v2.money_management.inbound_transfer.bank_debit_queued',
  'v2.money_management.inbound_transfer.bank_debit_returned',
  'v2.money_management.inbound_transfer.bank_debit_succeeded',
  'v2.money_management.outbound_payment.canceled',
  'v2.money_management.outbound_payment.created',
  'v2.money_management.outbound_payment.failed',
  'v2.money_management.outbound_payment.posted',
  'v2.money_management.outbound_payment.returned',
  'v2.money_management.outbound_payment.under_review',
  'v2.money_management.outbound_payment.updated',
  'v2.money_management.outbound_transfer.canceled',
  'v2.money_management.outbound_transfer.created',
  'v2.money_management.outbound_transfer.failed',
  'v2.money_management.outbound_transfer.posted',
  'v2.money_management.outbound_transfer.returned',
  'v2.money_management.outbound_transfer.under_review',
  'v2.money_management.outbound_transfer.updated',
  'v2.money_management.payout_method.created',
  'v2.money_management.payout_method.updated',
  'v2.money_management.received_credit.available',
  'v2.money_management.received_credit.failed',
  'v2.money_management.received_credit.returned',
  'v2.money_management.received_credit.succeeded',
  'v2.money_management.received_debit.canceled',
  'v2.money_management.received_debit.failed',
  'v2.money_management.received_debit.pending',
  'v2.money_management.received_debit.succeeded',
  'v2.money_management.received_debit.updated',
  'v2.money_management.recipient_verification.created',
  'v2.money_management.recipient_verification.updated',
  'v2.money_management.transaction.created',
  'v2.money_management.transaction.updated',
  'v2.orchestrated_commerce.agreement.confirmed',
  'v2.orchestrated_commerce.agreement.created',
  'v2.orchestrated_commerce.agreement.partially_confirmed',
  'v2.orchestrated_commerce.agreement.terminated',
  'v2.payments.off_session_payment.attempt_failed',
  'v2.payments.off_session_payment.attempt_started',
  'v2.payments.off_session_payment.authorization_attempt_failed',
  'v2.payments.off_session_payment.authorization_attempt_started',
  'v2.payments.off_session_payment.canceled',
  'v2.payments.off_session_payment.created',
  'v2.payments.off_session_payment.failed',
  'v2.payments.off_session_payment.paused',
  'v2.payments.off_session_payment.requires_capture',
  'v2.payments.off_session_payment.resumed',
  'v2.payments.off_session_payment.succeeded',
  'v2.payments.settlement_allocation_intent.canceled',
  'v2.payments.settlement_allocation_intent.created',
  'v2.payments.settlement_allocation_intent.errored',
  'v2.payments.settlement_allocation_intent.funds_not_received',
  'v2.payments.settlement_allocation_intent.matched',
  'v2.payments.settlement_allocation_intent.not_found',
  'v2.payments.settlement_allocation_intent.settled',
  'v2.payments.settlement_allocation_intent.submitted',
  'v2.payments.settlement_allocation_intent_split.canceled',
  'v2.payments.settlement_allocation_intent_split.created',
  'v2.payments.settlement_allocation_intent_split.settled',
  'v2.reporting.report_run.created',
  'v2.reporting.report_run.failed',
  'v2.reporting.report_run.succeeded',
  'v2.reporting.report_run.updated',
  'v2.signals.account_signal.fraudulent_merchant_ready',
  'v2.signals.account_signal.merchant_delinquency_ready',
  // event-types: The end of the section generated from our OpenAPI spec
]);

export class StripeEventNotificationHandler {
  private registeredHandlers: Record<string, HandlerCallback> = {};
  private hasHandledEvent = false;

  // eslint-disable-next-line no-useless-constructor
  constructor(
    private client: Stripe,
    private webhookSecret: string,
    private fallbackCallback: FallbackCallback
  ) {}

  // these types are duplicated in the manual types
  public on<T extends Stripe.V2.Core.EventNotification['type']>(
    type: T,
    callback: (
      event: Extract<Stripe.V2.Core.EventNotification, {type: T}>,
      client: Stripe
    ) => Promise<void>
  ): this;
  public on(type: string, callback: HandlerCallback): this {
    if (this.hasHandledEvent) {
      throw new Error(
        'Cannot register new handlers after an event has been handled. This is indicative of a bug.'
      );
    }
    // the matched types are validated by the type system
    if (this.registeredHandlers[type]) {
      throw new Error(`Handler already registered for event type: ${type}`);
    }

    this.registeredHandlers[type] = callback;
    return this;
  }

  public registeredEventTypes(): string[] {
    const keys = Object.keys(this.registeredHandlers);
    keys.sort();
    return keys;
  }

  public async handle(
    // these types are duplicated in the manual types, so they're just here for internal use
    rawBody: string | Uint8Array,
    signature: string | Uint8Array
  ): Promise<void> {
    // we're not worried about thread safety here because we expect callbacks will be registered synchronously on app startup
    this.hasHandledEvent = true;
    const event = this.client.parseEventNotification(
      rawBody,
      signature,
      this.webhookSecret
    );

    // Create a new client with the event's context instead of modifying the shared client
    // This ensures thread-safety when processing webhooks in parallel
    // We create a shallow copy and override _api with a new object containing the event context
    // This reuses expensive resources like httpClient (Flyweight pattern)
    const eventClient = Object.create(Object.getPrototypeOf(this.client));
    Object.assign(eventClient, this.client);
    eventClient._api = {
      ...this.client._api,
      stripeContext: event.context,
    };

    const handler = this.registeredHandlers[event.type];
    if (handler) {
      return await handler(event, eventClient);
    } else {
      return await this.fallbackCallback(
        event as Events.UnknownEventNotification,
        eventClient,
        {
          isKnownEventType: KNOWN_EVENT_TYPES.has(event.type),
        }
      );
    }
  }
}
