name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - beta
      - sdk-release/**
      - feature/**
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master
      - beta
      - private-preview
      - sdk-release/**
      - feature/**

permissions: {}

jobs:
  build:
    name: 'Static Checks'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read

    steps:
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '22'

      - name: Verify Linting
        run: just lint-check

      - name: Verify Formatting
        run: just format-check

  test:
    name: Test (${{ matrix.node }}, ${{ matrix.os }})
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-24.04'
        node:
          # should include even numbers >= 18
          # see: https://docs.stripe.com/sdks/versioning?lang=node#stripe-sdk-language-version-support-policy
          # https://endoflife.date/nodejs

          # note that starting in Oct 2026, every version will be LTS, so it's not just even numbers anymore
          # see: https://nodejs.org/en/blog/announcements/evolving-the-nodejs-release-schedule
          # - '26' # not yet compatible with mocha's yargs dependency
          - '24'
          - '22'
          - '20'
          - '18'
        include:
          - os: windows-latest
            # use any modern-ish version
            node: '24'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: ${{ matrix.node }}

      - name: Print Node.js version
        run: node -v

      # used for one of the integration tests
      - name: Setup Deno
        uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: v1.x

      - name: Print Deno version
        run: deno -V

      - uses: stripe/openapi/actions/stripe-mock@master

      - name: Test
        run: just ci-test

  publish:
    name: Publish
    if: >-
      (github.event_name == 'workflow_dispatch' || github.event_name == 'push') &&
      startsWith(github.ref, 'refs/tags/v')
    needs: [build, test]
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
      id-token: write # Required for OIDC
    steps:
      # just is called in `yarn prepack`, which is called during the `publish` operation
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@11
      - name: Publish to NPM
        run: |
          set -euxo pipefail
          VERSION=$(cat package.json | jq -r '.version')
          # use the tag correlating to this release channel
          NPM_TAG=$(cat package.json | jq -r '.version | if contains("beta") then "public-preview" else if contains("alpha") then "private-preview" else "latest" end end')
          echo "Publishing $VERSION with $NPM_TAG tag."
          npm publish --tag $NPM_TAG
      - uses: stripe/openapi/actions/notify-release@master
        if: always()
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
